### ISSUE TITLE
Question - How would one update the curtain view controller?

### ISSUE THREAD

**Issue by naturalui** [multimediasuite/SweetCurtain#10]
I am programmatically creating the CurtainController:

AppDelegate.swift
```contentViewController = MainViewController()
    curtainViewController = TestSheetViewController()
    curtainController = CurtainController(content: contentViewController!, curtain: curtainViewController!)
    curtainController?.curtain.minHeightCoefficient = 0.0
    curtainController?.curtain.midHeightCoefficient = 0.57
    curtainController?.curtain.maxHeightCoefficient = 0.98
    curtainController?.curtain.swipeResistance = .normal
    curtainController?.curtain.movingDuration = 0.5
    curtainController?.curtain.topBounce = true
    curtainController?.curtain.bottomBounce = true
    curtainController?.curtain.showsHandleIndicator = false
    curtainController?.curtainDelegate = self
    window.rootViewController = curtainController!
```

AnotherViewController.swift
```
// TODO: How do we push updated content to the curtain view?
//let testVC = UIViewController()
//testVC.view.backgroundColor = UIColor.red
//self.appDelegate.curtainViewController = testVC
self.curtainController?.moveCurtain(to: .mid, animated: true)
```

And in another ViewController I am able to show the view, however what is good way to updating the curtainViewController? e.g. if I want to use a different VC.

**Comment by ihormalovanyi** [comment]
Hi @naturalui 
Thank you for your question!

You have 2 ways to implement what you want.
1: Use Navigation Controller as Curtain and make transition your want when you need it. 
2: Use an empty view controller as Curtain then add your controller as a child and its view as subview. Then you can manage your controllers children as you want.

**Comment by naturalui** [comment]
Thanks @multimediasuite really love the library so far. 

For option is there a way to access the curtain view controller safely through the CurtainController?
e.g.

AppDelegate.swift
```
public curtainViewController = TestSheetViewController()
curtainController = CurtainController(content: contentViewController!, curtain: curtainViewController!)
...
```

AnotherViewController.swift
```
self.appDelegate.curtainViewController.backgroundColor = .red // This does not seem to work
//self.curtainController?.curtain.viewController // Does something like this exist?
self.curtainController?.moveCurtain(to: .mid, animated: true)
...
```

I'm just not sure how to best access the view to update it... even simple things like changing BG color.

**Comment by ihormalovanyi** [comment]
There are undocumented properties in CurtainController. You can find 2 public properties: curtainViewController and contentViewController. It was added in the last framework update.
```self.curtainController?.curtainViewController.view.backgroundColor = .red```

**Comment by naturalui** [comment]
Ahh yes this is exactly what I was looking for, however it seems to be read only, would it be valid to try and replace the VC before showing it? This would be simple way to replace the contents. Maybe a function like `self.curtainController?.updateViewController(newVC)`

![image](https://user-images.githubusercontent.com/1953861/75754881-5cf2c600-5ce2-11ea-96ed-444a5dd63f89.png)

**Comment by naturalui** [comment]
This did the trick but may be nice connivence function :) 

```  
let testVC = UIViewController()
testVC.view.backgroundColor = UIColor.red
self.curtainController?.curtainViewController.add(testVC)
self.curtainController?.moveCurtain(to: .mid, animated: true)
```

Assuming you have this extension:

```
extension UIViewController {
    func add(_ child: UIViewController) {
        addChild(child)
        view.addSubview(child.view)
        child.didMove(toParent: self)
    }

    func remove() {
        // Just to be safe, we check that this view controller
        // is actually added to a parent before removing it.
        guard parent != nil else {
            return
        }

        willMove(toParent: nil)
        view.removeFromSuperview()
        removeFromParent()
    }
}
```
